controller:
  kind: DaemonSet

  config:
    enable-access-log: "true"
    enable-snippet-annotations: "true"
    use-forwarded-headers: "true"
    enable-rewrite-log: "true"
    compute-full-forwarded-for: "true"
    custom-http-errors: ""

  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      labels:
        app: ingress-nginx
      type: ClusterIP
      port: 10254

  extraArgs:
    enable-ssl-passthrough: "true"

  extraConfig:
    http-snippet: |
      server {
        listen 8080;
        location /healthz {
          return 200 "OK";
        }
      }

  addHeaders:
    X-Health-Check: "OK"
